import Head from 'next/head';
import React from 'react';
import { Container, Box } from '@mui/material';
import imgs from '../assets/dashboard-logo/dashboard-logo.png';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <Container maxWidth="sm" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100vh' }}>
        <Box component="div" style={{ marginBottom: '20px' }}>
          <img src={imgs.src} alt="Dashboard Logo" style={{ width: '600px', height: '150px' }} />
        </Box>
      </Container>
    </>
  );
}
